# Generated by Django 4.0.4 on 2022-07-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verify_otp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
